# Generated by Django 3.1 on 2020-08-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Course subject, i.e. CS, MATH', max_length=10)),
                ('code', models.CharField(help_text='Numbers/characters after subject for the course', max_length=10)),
            ],
            options={
                'ordering': ['subject', 'code'],
                'unique_together': {('subject', 'code')},
            },
        ),
    ]
