# Generated by Django 3.1 on 2020-08-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together={('firstName', 'lastName')},
        ),
    ]
