# Generated by Django 3.1 on 2020-08-18 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['firstName', 'lastName'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="i.e. 'Winter 2020'", max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.term')),
            ],
            options={
                'ordering': ['course', 'term'],
                'unique_together': {('course', 'term')},
            },
        ),
        migrations.CreateModel(
            name='ClassOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNum', models.CharField(max_length=10)),
                ('sectionName', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('campus', models.CharField(max_length=10)),
                ('associatedClass', models.CharField(max_length=10)),
                ('relComp1', models.CharField(max_length=10, null=True)),
                ('relComp2', models.CharField(max_length=10, null=True)),
                ('enrollmentCapacity', models.IntegerField()),
                ('enrollmentTotal', models.IntegerField()),
                ('courseOffering', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.courseoffering')),
            ],
            options={
                'ordering': ['sectionName'],
                'unique_together': {('classNum', 'courseOffering')},
            },
        ),
        migrations.CreateModel(
            name='ClassLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.CharField(max_length=10, null=True)),
                ('endDate', models.CharField(max_length=10, null=True)),
                ('startTime', models.CharField(max_length=10, null=True)),
                ('endTime', models.CharField(max_length=10, null=True)),
                ('weekdays', models.CharField(max_length=10, null=True)),
                ('building', models.CharField(max_length=100, null=True)),
                ('room', models.CharField(max_length=100, null=True)),
                ('classOffering', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.classoffering')),
                ('instructor', models.ManyToManyField(to='catalog.Instructor')),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.subject'),
        ),
    ]
