# Generated by Django 3.1 on 2020-08-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="i.e. 'Winter 2020'", max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.course')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.term')),
            ],
            options={
                'ordering': ['course', 'term'],
                'unique_together': {('course', 'term')},
            },
        ),
    ]
