# Generated by Django 3.1 on 2020-08-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_courseoffering_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['firstName', 'lastName'],
            },
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='academicLevel',
            field=models.CharField(default='undergraduate', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClassOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classNum', models.CharField(max_length=10)),
                ('sectionName', models.CharField(max_length=10)),
                ('topic', models.CharField(max_length=100, null=True)),
                ('campus', models.CharField(max_length=10)),
                ('enrollmentCapacity', models.IntegerField()),
                ('enrollmentTotal', models.IntegerField()),
                ('courseOffering', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.courseoffering')),
            ],
            options={
                'ordering': ['sectionName'],
                'unique_together': {('classNum', 'courseOffering')},
            },
        ),
        migrations.CreateModel(
            name='ClassLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.CharField(max_length=10, null=True)),
                ('endDate', models.CharField(max_length=10, null=True)),
                ('startTime', models.CharField(max_length=10, null=True)),
                ('endTime', models.CharField(max_length=10, null=True)),
                ('weekdays', models.CharField(max_length=10, null=True)),
                ('building', models.CharField(max_length=100, null=True)),
                ('room', models.CharField(max_length=100, null=True)),
                ('classOffering', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalog.classoffering')),
                ('instructor', models.ManyToManyField(to='catalog.Instructor')),
            ],
            options={
                'ordering': ['startDate'],
            },
        ),
    ]
