# Generated by Django 3.1 on 2020-08-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200819_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classreserve',
            name='enrollmentCapacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='classreserve',
            name='enrollmentTotal',
            field=models.IntegerField(null=True),
        ),
    ]
